name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Build
        run: ./build.sh

      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          path: |
            ./build/*.pkg
          if-no-files-found: error
