name: Release

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      version:
        description: "Version Number"
        required: true
        default: "0.0.1"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: master
          path: artefacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          name: "v${{ github.event.inputs.version }}"
          draft: false
          prerelease: false
          files: ./artefacts/*
