name: Release

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      version:
        description: "Version Number"
        required: true
        default: "0.0.1"

jobs:
  build-and-release:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        # TODO: check if Mac can build for all platforms (except standalone)
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: master
          path: artefacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          name: "v${{ github.event.inputs.version }}"
          draft: false
          prerelease: false
          files: ./artefacts/*
