name: Release

# TODO: Replace manual trigger with tagging trigger
on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      version:
        description: "Version Number"
        required: true
        default: "0.0.1"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          branch: main
          path: artefacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          # TODO: Remove this when using version tag trigger (default behaviour)
          tag_name: "v${{ github.event.inputs.version }}"
          draft: false
          prerelease: false
          files: ./artefacts/*
          fail_on_unmatched_files: true
